// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCltjZDtJGYjp01Uhdp92MPVXAtaG7O1LE',
    appId: '1:343397250988:web:97ce845d6d3374d1b06c09',
    messagingSenderId: '343397250988',
    projectId: 'lifely-app-56c50',
    authDomain: 'lifely-app-56c50.firebaseapp.com',
    storageBucket: 'lifely-app-56c50.firebasestorage.app',
    measurementId: 'G-76KJ9D6FPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA62cJuhjGKpxdeREcZOwAdv0p7ReCC3Y',
    appId: '1:343397250988:android:4e19616089e11afab06c09',
    messagingSenderId: '343397250988',
    projectId: 'lifely-app-56c50',
    storageBucket: 'lifely-app-56c50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa1odifJO9juLV8D7e-1Ieb-aZauFnz1s',
    appId: '1:343397250988:ios:28fade4dbc041e73b06c09',
    messagingSenderId: '343397250988',
    projectId: 'lifely-app-56c50',
    storageBucket: 'lifely-app-56c50.firebasestorage.app',
    iosBundleId: 'com.example.lifelyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa1odifJO9juLV8D7e-1Ieb-aZauFnz1s',
    appId: '1:343397250988:ios:28fade4dbc041e73b06c09',
    messagingSenderId: '343397250988',
    projectId: 'lifely-app-56c50',
    storageBucket: 'lifely-app-56c50.firebasestorage.app',
    iosBundleId: 'com.example.lifelyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCltjZDtJGYjp01Uhdp92MPVXAtaG7O1LE',
    appId: '1:343397250988:web:9a2e4806fdee72a1b06c09',
    messagingSenderId: '343397250988',
    projectId: 'lifely-app-56c50',
    authDomain: 'lifely-app-56c50.firebaseapp.com',
    storageBucket: 'lifely-app-56c50.firebasestorage.app',
    measurementId: 'G-9EWXKYCZD8',
  );
}
